name: Tests

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: ./.github/actions/setup
      # source .envrc instead of direnv setup
      - name: Setup
        run: |
          source .envrc
      - name: Lint
        run: |
          pnpm run lint
      - name: Test
        run: |
          pnpm run test
